import { createElement } from '@lwc/engine-dom';
import HealthPlanManager from 'c/healthPlanManager';
//Test Suite Definition
describe('c-health-plan-manager', () => {
    //DOM Cleanup
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Create the component instance
        const element = createElement('c-health-plan-manager', {
            is: HealthPlanManager
        });
        
        // Attach it to the DOM
        document.body.appendChild(element);
        // A placeholder assertion
        expect(1).toBe(1);
    });
});
