name: Compare Orgs Metadata
on:
  workflow_dispatch:
    inputs:
      SRC_ORG_ALIAS:
        type: string
        description: "Alias for the Source Salesforce org"
        required: true
        default: "SrcOrgAlias"
      DST_ORG_ALIAS:
        type: string
        description: "Alias for the Destination Salesforce org"
        required: true
        default: "DstOrgAlias"

env:
  SRC_ORG_ALIAS: ${{ github.event.inputs.SRC_ORG_ALIAS }}
  DST_ORG_ALIAS: ${{ github.event.inputs.DST_ORG_ALIAS }}

jobs:
  compare_metadata:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Install Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 'Install Salesforce CLI'
        run: npm install @salesforce/cli --global

      - name: Verify Salesforce CLI
        run: |
          npm update --global @salesforce/cli
          sf plugins:update
          sf --version
          
      #- name: 'Install jq'
      #  run: sudo apt-get update && sudo apt-get install -y jq

      - name: 'Authenticate Source & Destination Orgs'
        run: |
          echo "${{ secrets.SRC_ORG_SFDX_URL }}" | sf org login sfdx-url --alias $SRC_ORG_ALIAS --set-default --sfdx-url-stdin
          echo "${{ secrets.DST_ORG_SFDX_URL }}" | sf org login sfdx-url --alias $DST_ORG_ALIAS --set-default --sfdx-url-stdin
          sf org list
        
      - name: 'Create Source Project with manifest, Navigate to the Source project folder, Download metadata using SFDX'
        run: |
          # Generate project and manifest
          sf project generate --name "src-org-metadata" --manifest
          
          if test -f "./config/package.xml"; then
             echo "./config/package.xml file exists"
             cp ./config/package.xml ./src-org-metadata/manifest
          fi
          
          cd "./src-org-metadata"
          
          # Retrieve metadata
          sf project retrieve start --target-org $SRC_ORG_ALIAS --manifest manifest/package.xml

      - name: 'Create Destination Project with manifest, Navigate to the Destination project folder, Download metadata using SFDX'
        run: |
          # Generate project and manifest
          sf project generate --name "dst-org-metadata" --manifest
          
          if test -f "./config/package.xml"; then
             echo "./config/package.xml file exists"
             cp ./config/package.xml ./dst-org-metadata/manifest
          fi
          
          cd "./dst-org-metadata"
          
          # Retrieve metadata
          sf project retrieve start --target-org $DST_ORG_ALIAS --manifest manifest/package.xml

      - name: 'Compare Source and Destination Metadata'
        run: |
          (diff -rq ./src-org-metadata/force-app ./dst-org-metadata/force-app | grep -E "differ|Only" || echo "No differences found") > metadata-diff.txt
          echo "Diff completed."

      - name: 'Write diff to GitHub Summary'
        run: |
          cat metadata-diff.txt
          echo '## Metadata Diff' >> $GITHUB_STEP_SUMMARY
          cat metadata-diff.txt >> $GITHUB_STEP_SUMMARY

      - name: 'Upload Diff Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: metadata-diff
          path: metadata-diff.txt
