name: Salesforce Dependency Analysis with sfpowerkit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday at midnight
env:
  ORG_ALIAS: org_alias
  REPORT_RECIPIENT: "bassemmarji@gmail.com"

jobs:
  dependency-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Install Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Key fix: Use Node 18

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 make g++

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf --version

      - name: Install sfpowerkit
        run: echo "Y" | sf plugins install sfpowerkit@4.1.4

      - name: Authenticate to Org
        run: echo "${{ secrets.ORG_SFDX_URL }}" | sf org login sfdx-url --alias $ORG_ALIAS --set-default --sfdx-url-stdin
      
      - name: 'Validate Authenticated Org'
        run: sf org list

      - name: Generate Dependency Report
        run: |
          mkdir -p reports
          # sf sfpowerkit:org:dependency:list \
          #  -u $ORG_ALIAS \
          #  --json \
          #  > reports/dependencies.json || echo "No dependencies found"
          sf sfpowerkit:org:orgcoverage \
             -u $ORG_ALIAS \
             --json \
             > reports/dependencies.json || echo "No dependencies found"
      - name: 'List Generated Files'
        run: |
          echo "📄 Listing files in reports:"
          ls -la $GITHUB_WORKSPACE/reports
