name: Generate Salesforce ERD

on:
  workflow_dispatch:

env:
  ORG_ALIAS: org_alias
  OUTPUT_FOLDER: erd-output

jobs:
  generate_erd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Install sfdx-erd Plugin
        run: |
          echo "Y" | sf plugins install sfdx-erd

      - name: Authenticate to Org
        run: echo "${{ secrets.ORG_SFDX_URL }}" | sf org login sfdx-url --alias $ORG_ALIAS --set-default --sfdx-url-stdin

      - name: Create Output Directory
        run: mkdir -p $OUTPUT_FOLDER

      - name: Generate ERD Diagrams
        run: |
          sf erd generate --targetusername $ORG_ALIAS --outputDir $OUTPUT_FOLDER --format svg --includeAllCustomObjects

      - name: Upload ERD Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ERD Diagrams
          path: ${{ env.OUTPUT_FOLDER }}
