name: Call DeepSeek API

on:
  workflow_dispatch:  # Manually trigger the workflow
  schedule:
    - cron: '0 12 * * *'  # Runs at 12 PM UTC daily (optional)

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Call DeepSeek API
        env:
          API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          python -c '
          import requests
          import os

          API_KEY = os.getenv("API_KEY")
          API_URL = "https://api.deepseek.com/v1/chat"  # Hypothetical endpoint

          headers = {
              "Authorization": f"Bearer {API_KEY}",
              "Content-Type": "application/json"
          }

          data = {
              "model": "deepseek-chat",
              "messages": [{"role": "user", "content": "Hello!"}]
          }

          response = requests.post(API_URL, headers=headers, json=data)
          print(response.json())
          '
