name: Windows Eclipse Maven Setup

on:
  workflow_dispatch:
    inputs:
      ORG_ALIAS:
        type: string
        description: "Salesforce org alias"
        required: true
        default: "dev"

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Example cache step for Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download Eclipse Oxygen 4.7
        run: |
          Invoke-WebRequest -Uri https://archive.eclipse.org/eclipse/downloads/drops/R-4.7-201706111000/eclipse-SDK-4.7-win32-x86_64.zip -OutFile eclipse.zip
          Expand-Archive eclipse.zip -DestinationPath C:\eclipse

      - name: Install BPMN2 plugin
        run: |
          C:\eclipse\eclipse.exe -application org.eclipse.equinox.p2.director -noSplash -repository https://download.eclipse.org/bpmn2-modeler/releases/ -installIU org.eclipse.bpmn2.modeler.feature.feature.group

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.2.1
        with:
          maven-version: '3.8.5'
          java-version: '8'

      - name: Verify Maven version
        run: mvn -version

      - name: Configure git
        run: |
          git config --global user.name "bassemmarji"
          git config --global user.email "bassemmarji@gmail.com"

      - name: Compress Eclipse folder
        run: |
          Compress-Archive -Path C:\eclipse\* -DestinationPath C:\eclipse.zip

      - name: Add compressed Eclipse archive to repo
        run: |
          mkdir eclipse_archive
          move C:\eclipse.zip eclipse_archive\
          git add eclipse_archive/eclipse.zip
          git commit -m "Add compressed Eclipse Oxygen setup"
          git push
