# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Backup Org

# When the workflow will run
on:
 workflow_dispatch:
   # Define parameters for the workflow in order to pass parameters to it when triggered.
   # This makes the workflow more flexible and adaptable.
   inputs:
     # this will be refered to as ${{ github.event.inputs.commit_text }}
     commit_message:
       description: 'Commit message to use'    
       required: true
       default: 'Manual Backup Commit'

env:
  # Defining Global environment variables accessible to all jobs and steps. 
  ORG_ALIAS: org_alias 
  METADATA_FOLDERNAME: backupMetadata
  DATA_FOLDERNAME: backupData
  
jobs:
  backup_job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Install Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 'Install Salesforce Client'
        run: |
          npm install @salesforce/cli --global
          
      - name: 'Authorize to the org'
        run: echo "${{ secrets.ORG_SFDX_URL }}" | sf org login sfdx-url --alias $ORG_ALIAS --setdefaultusername --sfdx-url-stdin

