name: Send Webhook

on:
  workflow_dispatch:
    inputs:
      ORG_ALIAS:
        type: string
        description: "Alias for the Salesforce org"
        required: true
        default: "orgAlias"

env:
  ORG_ALIAS: ${{ github.event.inputs.ORG_ALIAS }}

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Install Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 'Install Salesforce CLI'
        run: npm install @salesforce/cli --global

      - name: Verify Salesforce CLI
        run: |
          npm update --global @salesforce/cli
          sf plugins:update
          sf --version

      - name: 'Install jq'
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: 'Authenticate to the Org'
        run: echo "${{ secrets.ORG_SFDX_URL }}" | sf org login sfdx-url --alias $ORG_ALIAS --set-default --sfdx-url-stdin
      
      - name: 'Get Access Token'
        id: get_token
        run: |
          # Method 1: Remove --verbose flag to avoid warning
          OUTPUT=$(sf org display --target-org $ORG_ALIAS --json)
          
          # Parse JSON and extract values (without verbose, accessToken might not be available)
          ACCESS_TOKEN=$(echo "$OUTPUT" | jq -r '.result.accessToken // empty')
          INSTANCE_URL=$(echo "$OUTPUT" | jq -r '.result.instanceUrl // empty')

          # Debug: Show extracted values (mask sensitive token)
          echo "Extracted ACCESS_TOKEN: ${ACCESS_TOKEN:0:10}..."
          echo "Extracted INSTANCE_URL: $INSTANCE_URL"

          
          # Validate that we got valid values
          if [ "$ACCESS_TOKEN" = "null" ] || [ -z "$ACCESS_TOKEN" ]; then
            echo "ERROR: Failed to extract access token"
            exit 1
          fi
          
          if [ "$INSTANCE_URL" = "null" ] || [ -z "$INSTANCE_URL" ]; then
            echo "ERROR: Failed to extract instance URL"
            exit 1
          fi
          
          # Set environment variables for subsequent steps
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
          echo "INSTANCE_URL=$INSTANCE_URL" >> $GITHUB_ENV
          
          # Also set as step outputs if you need them in other jobs
          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
          echo "instance_url=$INSTANCE_URL" >> $GITHUB_OUTPUT

      - name: Debug Token Validity
        run: |
          echo "Testing token validity..."
          RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" \
                         -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
                         -H "Content-Type: application/json" \
                         "${{ env.INSTANCE_URL }}/services/data/v59.0/query/?q=SELECT+Id+FROM+Organization")
          
          HTTP_STATUS=$(echo "$RESPONSE" | grep "HTTP_STATUS" | cut -d: -f2)
          BODY=$(echo "$RESPONSE" | sed '/HTTP_STATUS/d')
          
          echo "HTTP Status: $HTTP_STATUS"
          echo "Response Body: $BODY"
          
          if [ "$HTTP_STATUS" != "200" ]; then
            echo "Token validation failed!"
          else
            echo "Token is valid!"
          fi

      - name: Set Workflow Status
        run: |
          # Set STATUS based on previous steps
          if [ "${{ job.status }}" = "success" ]; then
            echo "STATUS=success" >> $GITHUB_ENV
          else
            echo "STATUS=failure" >> $GITHUB_ENV
          fi

      - name: Test Webhook Endpoint First
        run: |
          echo "Testing webhook endpoint accessibility..."
          WEBHOOK_URL="${{ env.INSTANCE_URL }}/services/apexrest/github/webhook"
          echo "Webhook URL: $WEBHOOK_URL"
          
          # Test with curl first
          RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" \
                         -X POST \
                         -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
                         -H "Content-Type: application/json" \
                         -d '{"test": "connection"}' \
                         --max-time 30 \
                         "$WEBHOOK_URL")
          
          HTTP_STATUS=$(echo "$RESPONSE" | grep "HTTP_STATUS" | cut -d: -f2)
          BODY=$(echo "$RESPONSE" | sed '/HTTP_STATUS/d')
          
          echo "Test HTTP Status: $HTTP_STATUS"
          echo "Test Response Body: $BODY"

