name: Backup Org Metadata and Data

# When the workflow will run
on:
 #schedule:
  # Runs at 12:00 UTC every day.
  # - cron: '0 12 * * *'
  
 # To manually trigger the workflow directly from Github UI or via the Github API.
 # This is particularly useful for workflows that perform manual tasks such as deploying software to production
 # database migrations, or any process that requires manual oversight.
 workflow_dispatch:
   # Define parameters for the workflow in order to pass parameters to it when triggered.
   # This makes the workflow more flexible and adaptable.
   inputs:
     # this will be refered to as ${{ github.event.inputs.commit_text }}
     commit_text:
       description: 'Commit Message'    
       required: true
       default: 'Backup of Org'

env:
  # Defining Global environment variables accessible to all jobs and steps. 
  ORG_ALIAS: org_alias 
  METADATA_FOLDERNAME: backupMetadata
  DATA_FOLDERNAME: backupData
  
jobs:
 main_job:
   runs-on: ubuntu-latest
   steps:
     - name: 'Print Workflow Context Variables'
       run: |
        echo "This job was triggered by:"
        echo " * Actor = ${{ github.actor }}" 
        echo " * Event = ${{ github.event_name }}"  
        echo " * Repository = ${{ github.repository }}"
        echo " * Branch = ${{ github.ref }}"
        echo " * OS = ${{runner.os}} server hosted by Github."
